version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mah3uz-gopeed_web_1
      APP_PORT: 9999
  web:
    image: liwei2633/gopeed:v1.9.3@sha256:3ad6274077eb81282f0782efb9824783bb2f969c3a4ce966f0d959cc53c23eae
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - ${APP_DATA_DIR}/data/storage:/app/storage
      - ${UMBREL_ROOT}/data/storage/downloads:/app/Downloads
