version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mah3uz-gopeed_web_1
      APP_PORT: 9999
  web:
    image: liwei2633/gopeed:v1.9.1@sha256:cc35b801f54a4e681abd67bc29a2939b939b6054b81ac477cc8fbceecdaad7f5
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - ${APP_DATA_DIR}/data/storage:/app/storage
      - ${UMBREL_ROOT}/data/storage/downloads:/app/Downloads
